
export default {
   CHAR_MATRIX: [],
   NUMERO_NOMBRE: [],
   NUMERO_HEREDITARIO: [],
   NUMERO_ALMA: [],
   NUMERO_PERSONALIDAD: [],
   MISION_COSMICA: [],
   NUMERO_MAESTRO: [],
   NUMERO_POTENCIAL: [],
   NUMERO_INICIACION_ESPIRITUAL: [],
   NUMERO_EQUILIBRIO: []
}